### ISSUE TITLE
Crashing with new CSV output update

### ISSUE THREAD

**Issue by bafflerbach** [uw-cmg/MAST-ML#204]
It looks like that new change to output CSVs for summary plots in cross validation is causing a crash.

[ERROR] arrays must all be same length
Traceback (most recent call last):
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 61, in main
    mastml_run(conf_path, data_path, outdir)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 865, in mastml_run
    runs = do_all_combos(X, y, df) # calls do_one_splitter internally
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 607, in do_all_combos
    return do_models_splits(models, original_models)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 603, in do_models_splits
    runs = do_one_splitter(X, y, model_instance, subsubdir, trains_tests, grouping_data)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 861, in do_one_splitter
    make_pred_vs_true_plots(model=model)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 839, in make_pred_vs_true_plots
    join(main_path, 'best_worst_split'), label=y.name)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\plot_helper.py", line 169, in wrapper
    return plot_func(*args, **kwargs)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\plot_helper.py", line 741, in plot_best_worst_split
    'worst run pred': worst_run['y_test_pred'], 'worst run true': worst_run['y_test_true']})
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\site-packages\pandas\core\frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\site-packages\pandas\core\internals\construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\site-packages\pandas\core\internals\construction.py", line 51, in arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\site-packages\pandas\core\internals\construction.py", line 317, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length
Traceback (most recent call last):
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 1225, in <module>
    main(conf_path, data_path, outdir, verbosity)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 70, in main
    raise e
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 61, in main
    mastml_run(conf_path, data_path, outdir)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 865, in mastml_run
    runs = do_all_combos(X, y, df) # calls do_one_splitter internally
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 607, in do_all_combos
    return do_models_splits(models, original_models)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 603, in do_models_splits
    runs = do_one_splitter(X, y, model_instance, subsubdir, trains_tests, grouping_data)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 861, in do_one_splitter
    make_pred_vs_true_plots(model=model)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\mastml_driver.py", line 839, in make_pred_vs_true_plots
    join(main_path, 'best_worst_split'), label=y.name)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\plot_helper.py", line 169, in wrapper
    return plot_func(*args, **kwargs)
  File "C:\Users\Ben\Desktop\MASTML_quicktest\MAST-ML-master\mastml\plot_helper.py", line 741, in plot_best_worst_split
    'worst run pred': worst_run['y_test_pred'], 'worst run true': worst_run['y_test_true']})
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\site-packages\pandas\core\frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\site-packages\pandas\core\internals\construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\site-packages\pandas\core\internals\construction.py", line 51, in arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\Ben\Anaconda3\envs\MASTML_2-8\lib\site-packages\pandas\core\internals\construction.py", line 317, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length

**Comment by rjacobs914** [comment]
Yes I saw this too. I just fixed it and pushed a change. The issue was sometimes the best and worst splits are different lengths
